# Generated by Django 4.2.2 on 2023-06-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appname", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="tag",
            field=models.CharField(
                choices=[
                    ("programming", "Programming"),
                    ("design", "design"),
                    ("video editing", "Video editing"),
                    ("marketing", "Marketing"),
                    ("misc", "Misc"),
                ],
                default="misc",
                max_length=20,
            ),
        ),
    ]
