# Generated by Django 4.2.2 on 2023-06-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appname", "0003_roadmap"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="tag",
            new_name="genre",
        ),
        migrations.RemoveField(
            model_name="roadmap",
            name="project_name",
        ),
        migrations.AddField(
            model_name="roadmap",
            name="description",
            field=models.TextField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="roadmap",
            name="genre",
            field=models.CharField(
                choices=[
                    ("programming", "Programming"),
                    ("design", "design"),
                    ("video editing", "Video editing"),
                    ("marketing", "Marketing"),
                    ("misc", "Misc"),
                ],
                default="misc",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="roadmap",
            name="skills",
            field=models.CharField(default=100, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="roadmap",
            name="title",
            field=models.CharField(default=100, max_length=100),
            preserve_default=False,
        ),
    ]
