# Generated by Django 4.2.2 on 2023-06-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "appname",
            "0004_rename_tag_project_genre_remove_roadmap_project_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_id",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
