# Generated by Django 4.2.2 on 2023-06-25 21:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appname", "0007_roadmap_difficulty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="difficulty",
        ),
    ]
