# Generated by Django 4.2.2 on 2023-06-26 00:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appname", "0008_remove_project_difficulty"),
    ]

    operations = [
        migrations.RenameField(
            model_name="roadmap",
            old_name="roadmap",
            new_name="generate_roadmap",
        ),
    ]
