# Generated by Django 4.2.2 on 2023-06-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appname", "0009_rename_roadmap_roadmap_generate_roadmap"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadmap",
            name="project_id",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
