# Generated by Django 4.2.2 on 2023-07-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appname", "0010_roadmap_project_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadmap",
            name="task",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
