# Generated by Django 4.2.2 on 2023-07-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appname", "0012_customuser"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
        migrations.AddField(
            model_name="customuser",
            name="bio",
            field=models.TextField(blank=True),
        ),
    ]
