# Generated by Django 4.2.2 on 2023-07-04 17:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appname", "0014_alter_customuser_options_remove_customuser_bio_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
