# Generated by Django 4.2.2 on 2023-07-08 01:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appname", "0017_alter_roadmap_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roadmap",
            name="user",
        ),
    ]
