# Generated by Django 4.2.2 on 2023-07-08 03:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appname", "0021_roadmap_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="tools",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="roadmap",
            name="tools",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
